const numbers = [
  { id: 1, content: 1, stat: "" },
  { id: 1, content: 1, stat: "" },
  { id: 2, content: 2, stat: "" },
  { id: 2, content: 2, stat: "" },
  { id: 3, content: 3, stat: "" },
  { id: 3, content: 3, stat: "" },
  { id: 4, content: 4, stat: "" },
  { id: 4, content: 4, stat: "" },
  { id: 5, content: 5, stat: "" },
  { id: 5, content: 5, stat: "" },
  { id: 6, content: 6, stat: "" },
  { id: 6, content: 6, stat: "" },
  { id: 7, content: 7, stat: "" },
  { id: 7, content: 7, stat: "" },
  { id: 8, content: 8, stat: "" },
  { id: 8, content: 8, stat: "" },
  { id: 9, content: 9, stat: "" },
  { id: 9, content: 9, stat: "" },
  { id: 10, content: 10, stat: "" },
  { id: 10, content: 10, stat: "" },
  { id: 11, content: 11, stat: "" },
  { id: 11, content: 11, stat: "" },
  { id: 12, content: 12, stat: "" },
  { id: 12, content: 12, stat: "" },
  { id: 13, content: 13, stat: "" },
  { id: 13, content: 13, stat: "" },
  { id: 14, content: 14, stat: "" },
  { id: 14, content: 14, stat: "" },
  { id: 15, content: 15, stat: "" },
  { id: 15, content: 15, stat: "" },
  { id: 16, content: 16, stat: "" },
  { id: 16, content: 16, stat: "" },
  { id: 17, content: 17, stat: "" },
  { id: 17, content: 17, stat: "" },
  { id: 18, content: 18, stat: "" },
  { id: 18, content: 18, stat: "" },
].sort(() => Math.random() - 0.5);

export default numbers;
