const numbers = [
  { id: 1, content: 1, classN: "" },
  { id: 1, content: 1, classN: "" },
  { id: 2, content: 2, classN: "" },
  { id: 2, content: 2, classN: "" },
  { id: 3, content: 3, classN: "" },
  { id: 3, content: 3, classN: "" },
  { id: 4, content: 4, classN: "" },
  { id: 4, content: 4, classN: "" },
  { id: 5, content: 5, classN: "" },
  { id: 5, content: 5, classN: "" },
  { id: 6, content: 6, classN: "" },
  { id: 6, content: 6, classN: "" },
  { id: 7, content: 7, classN: "" },
  { id: 7, content: 7, classN: "" },
  { id: 8, content: 8, classN: "" },
  { id: 8, content: 8, classN: "" },
  { id: 9, content: 9, classN: "" },
  { id: 9, content: 9, classN: "" },
  { id: 10, content: 10, classN: "" },
  { id: 10, content: 10, classN: "" },
  { id: 11, content: 11, classN: "" },
  { id: 11, content: 11, classN: "" },
  { id: 12, content: 12, classN: "" },
  { id: 12, content: 12, classN: "" },
  { id: 13, content: 13, classN: "" },
  { id: 13, content: 13, classN: "" },
  { id: 14, content: 14, classN: "" },
  { id: 14, content: 14, classN: "" },
  { id: 15, content: 15, classN: "" },
  { id: 15, content: 15, classN: "" },
  { id: 16, content: 16, classN: "" },
  { id: 16, content: 16, classN: "" },
  { id: 17, content: 17, classN: "" },
  { id: 17, content: 17, classN: "" },
  { id: 18, content: 18, classN: "" },
  { id: 18, content: 18, classN: "" },
].sort(() => Math.random() - 0.5);

export default numbers;
