export const icons = [
  { id: 1, content: "/ICONS/sun-solid.svg", stat: "" },
  { id: 1, content: "/ICONS/sun-solid.svg", stat: "" },
  { id: 2, content: "/ICONS/spider-solid.svg", stat: "" },
  { id: 2, content: "/ICONS/spider-solid.svg", stat: "" },
  { id: 3, content: "/ICONS/snowflake-regular.svg", stat: "" },
  { id: 3, content: "/ICONS/snowflake-regular.svg", stat: "" },
  { id: 4, content: "/ICONS/moon-regular.svg", stat: "" },
  { id: 4, content: "/ICONS/moon-regular.svg", stat: "" },
  { id: 5, content: "/ICONS/hand-solid.svg", stat: "" },
  { id: 5, content: "/ICONS/hand-solid.svg", stat: "" },
  { id: 6, content: "/ICONS/gem-regular.svg", stat: "" },
  { id: 6, content: "/ICONS/gem-regular.svg", stat: "" },
  { id: 7, content: "/ICONS/futbol-regular.svg", stat: "" },
  { id: 7, content: "/ICONS/futbol-regular.svg", stat: "" },
  { id: 8, content: "/ICONS/car-solid.svg", stat: "" },
  { id: 8, content: "/ICONS/car-solid.svg", stat: "" },
  { id: 9, content: "/ICONS/bottle-droplet-solid.svg", stat: "" },
  { id: 9, content: "/ICONS/bottle-droplet-solid.svg", stat: "" },
  { id: 10, content: "/ICONS/anchor-solid.svg", stat: "" },
  { id: 10, content: "/ICONS/anchor-solid.svg", stat: "" },
  { id: 11, content: "/ICONS/music-solid.svg", stat: "" },
  { id: 11, content: "/ICONS/music-solid.svg", stat: "" },
  { id: 12, content: "/ICONS/bell.svg", stat: "" },
  { id: 12, content: "/ICONS/bell.svg", stat: "" },
  { id: 13, content: "/ICONS/smile.svg", stat: "" },
  { id: 13, content: "/ICONS/smile.svg", stat: "" },
  { id: 14, content: "/ICONS/cup.svg", stat: "" },
  { id: 14, content: "/ICONS/cup.svg", stat: "" },
  { id: 15, content: "/ICONS/ghost.svg", stat: "" },
  { id: 15, content: "/ICONS/ghost.svg", stat: "" },
  { id: 16, content: "/ICONS/gift.svg", stat: "" },
  { id: 16, content: "/ICONS/gift.svg", stat: "" },
  { id: 17, content: "/ICONS/pen.svg", stat: "" },
  { id: 17, content: "/ICONS/pen.svg", stat: "" },
  { id: 18, content: "/ICONS/umbrella.svg", stat: "" },
  { id: 18, content: "/ICONS/umbrella.svg", stat: "" },
].sort(() => Math.random() - 0.5);

export const iconsMini = [
  { id: 1, content: "/ICONS/sun-solid.svg", stat: "" },
  { id: 1, content: "/ICONS/sun-solid.svg", stat: "" },
  { id: 2, content: "/ICONS/spider-solid.svg", stat: "" },
  { id: 2, content: "/ICONS/spider-solid.svg", stat: "" },
  { id: 3, content: "/ICONS/snowflake-regular.svg", stat: "" },
  { id: 3, content: "/ICONS/snowflake-regular.svg", stat: "" },
  { id: 4, content: "/ICONS/moon-regular.svg", stat: "" },
  { id: 4, content: "/ICONS/moon-regular.svg", stat: "" },
  { id: 5, content: "/ICONS/hand-solid.svg", stat: "" },
  { id: 5, content: "/ICONS/hand-solid.svg", stat: "" },
  { id: 6, content: "/ICONS/gem-regular.svg", stat: "" },
  { id: 6, content: "/ICONS/gem-regular.svg", stat: "" },
  { id: 7, content: "/ICONS/futbol-regular.svg", stat: "" },
  { id: 7, content: "/ICONS/futbol-regular.svg", stat: "" },
  { id: 8, content: "/ICONS/car-solid.svg", stat: "" },
  { id: 8, content: "/ICONS/car-solid.svg", stat: "" },
].sort(() => Math.random() - 0.5);
